prepare_data:
  path: "../data/cars.csv"
  save_path: "../data/cars_transformed.csv"
split_data:
  path: "../data/cars_transformed.csv"
  test_size: 0.2
  train_path: "../data/train.csv"
  test_path: "../data/test.csv"
train:
  cv: 3
  n_jobs: -1
  model_path: "../models/model.joblib"
  power_path: "../models/power.joblib"